name: Deployment Pipeline

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            sudo cd /var/www/viatom-prod
            pwd
            sudo git config --global --add safe.directory /var/www/viatom-prod
            sudo git config --global user.name "zhafranammar"
            sudo git config --global user.email "mzhafranammar@gmail.com"
            sudo git pull

# Path: .github\workflows\deploy.yml